### ISSUE TITLE
Invalid npm package

### ISSUE THREAD

**Issue by ViceIce** [andrei-markeev/camljs#10]
Hi,

the [npm package](https://www.npmjs.com/package/camljs) is invalid. The main script should be a [node module](https://nodejs.org/api/modules.html) or an [umd](https://github.com/umdjs/umd) file.

I can make a PR for building such  a file.

**Comment by andrei-markeev** [comment]
I am not managing the camljs npm package, someone else published camljs there. I'll request permissions.

**Comment by ViceIce** [comment]
OK.

**Comment by ViceIce** [comment]
Until you get the permissions, we can publish a new package as `caml-js` or something like that.

**Comment by andrei-markeev** [comment]
I got the access this morning! I'll address those issues in couple of days!

**Comment by andrei-markeev** [comment]
Should be fixed in v2.9.0!

**Comment by ViceIce** [comment]
One more problem. You recompile the d.ts file after browserify, which is overwriting the camljs.js file too.
You should add `--emitDeclarationOnly` to only emit the declarations or compile declarations before browserify.

PR #12 will fix that.
