### ISSUE TITLE
Support new CamlBuilder.Query().Where()

### ISSUE THREAD

**Issue by rlking1985** [andrei-markeev/camljs#16]
Hi Andrei,

Could you add support for new CamlBuilder.Query().

Apologies if this already an option and I have missed it.

I am working with plugins like SPServices and SPJS that require the **Query** tags. I could add them manually but would rather use your CamlJs.

```xml
<Query>
  <Where>
      <Eq>
          <FieldRef Name="Title" />
          <Value Type="Text">A Title Name</Value>
      </Eq>
  </Where>
</Query>
```

Modifying existing queries only works when the query tag is included. It would be nice to have the following CAMLJS object return the xml above.

```javascript
new CamlBuilder.Query().Where().TextField("Title").EqualTo("A Title Name").ToString();

```

**Comment by andrei-markeev** [comment]
I will take your proposal into work for the next version, but due to current schedule it might take several weeks until implementation is done.

Currently it is either "<View>" or "<Where>", so as a workaround you could use something like this:
```js
var where = new CamlBuilder.Where().TextField("Title").EqualTo("A Title Name").ToString();
var camlQuery = "<Query>" + where + "</Query>";
```

**Comment by rlking1985** [comment]
Thanks Andrei,

No rush, appreciate the work you have already done on this tool.

I have added a prototype .ToQuery() instead of .ToString() to achieve what you suggested. If you get time it would be great but if not, it's not a show stopper.

Cheers,

**Comment by rlking1985** [comment]
Andrei,

Just close this issue. It was a nice to have for simplicity with SPServices but is so low level it's not worth a change to your code base.
