### ISSUE TITLE
Error: Cannot read property 'create' of undefined

### ISSUE THREAD

**Issue by koehrlenguillaume** [andrei-markeev/camljs#19]
Hey Andrei, 

I would like to know if there is a way to use your library outside of SharePoint ? 
It seems your library need the sp.js script ? 

I'm asking you this question because I'm facing the following issue 
```javascript
Uncaught TypeError: Cannot read property 'create' of undefined
```

Thanks, 
Kind regards, 

Guillaume Koehrlen

**Comment by koehrlenguillaume** [comment]
I found the reason. 

You're currently using the `SP.XmlWriter` in the function `Builder.prototype.Finalize` (line 987). 
Outside of SharePoint or before it has been load we have the error 

```javascript 
Uncaught TypeError: Cannot read property 'create' of undefined
```

Do you have a workaround ?

**Comment by gunfus** [comment]
There is also a reference to SP.CamlQuery in Builder.prototype.FinalizeToSPQuery.

```javascript
Builder.prototype.FinalizeToSPQuery = function () {
      var camlQuery = this.Finalize();
      if (camlQuery.indexOf("<View") != 0)
      camlQuery = "<View><Query>" + camlQuery + "</Query></View>";
      var query = new SP.CamlQuery();
      query.set_viewXml(camlQuery);
      return query;
};
```
Would love a workaround for this.

**Comment by koehrlenguillaume** [comment]
I think the function regarding the `Builder.prototype.FinalizeToSPQuery` should stay like this. 
In fact, if you need to use SP.CamlQuery object, you're actualy using JSOM 
   --> So if you're using JSOM, sp.js should be loaded anyway and the SP.CamlQuery can be create without any issue

**Comment by middiu** [comment]
> I think the function regarding the `Builder.prototype.FinalizeToSPQuery` should stay like this.
> In fact, if you need to use SP.CamlQuery object, you're actualy using JSOM
> --> So if you're using JSOM, sp.js should be loaded anyway and the SP.CamlQuery can be create without any issue

I have the same issue developing with SPFx, and of course SP.XmlWriter is not loaded for me... any suggestion?

**Comment by andrei-markeev** [comment]
Guys, I don't know what happens, but I am completely unable to reproduce the issue.
I am trying to run the [SPFx example](https://github.com/andrei-markeev/camljs/tree/master/examples/spfx) this is included in this repo, and everything works just fine:

![image](https://user-images.githubusercontent.com/5181724/53015860-c6e05a80-3454-11e9-8b6c-41e3f7a37735.png)

**Comment by andrei-markeev** [comment]
I re-tested everything one more time, and unfortunately I cannot reproduce the issue.
It works very well both in workbench and after I deploy it to SP.

![image](https://user-images.githubusercontent.com/5181724/53021105-1c226900-3461-11e9-9cdb-d934977815de.png)

I'm using the [SPFx example](https://github.com/andrei-markeev/camljs/tree/master/examples/spfx) provided in this repo.

Can one of you guys share some minimal example where this issue can be reproduced?

**Comment by middiu** [comment]
Have you to drop the webpart in a Classic Page? I can see from your screenshot that you are using a Modern one.

Cheers

**Comment by andrei-markeev** [comment]
That also works for me:
![image](https://user-images.githubusercontent.com/5181724/53044287-3c6b1b80-3493-11e9-985d-fe126b8296f3.png)

Btw, what version of SPFx are you using? Maybe this happens only in certain version of SPFx?

**Comment by middiu** [comment]
This is strange.

Btw I use SPFx 1.7

To make it working I had to import/load all the legacy jsom js files sp.js, core.js etc etc

Wondering if it depends on the Sharepoint site template. It could be that certain templates load more js than others...

**Comment by andrei-markeev** [comment]
I recreated the example webpart from scratch using latest version of SPFx framework (1.7.1), packaged solution and deployed it using another name, and confirmed one more time that everything works well both on Classic and Modern pages.

Please check that you're including camljs correctly into your solution:

1. Open your existing SPFx solution
2. `npm i camljs`
3. Add following minimal example code somewhere in your webpart or React component:
```ts
import * as CamlBuilder from "camljs";
// ...
// then, e.g. in webpart's render method, or in React component's componentDidMount:
console.log(new CamlBuilder().View().ToString());
```
4. `gulp bundle --ship`
5. `gulp package-solution --ship`
6. Upload package to app catalog
7. Add your webpart to a page
8. Check devtools, it should log "<View />" into console

**Comment by andrei-markeev** [comment]
Please feel free to reopen the issue (and provide additional details of how to reproduce it) if you still have this problem.

**Comment by benjdewantara** [comment]
@koehrlenguillaume

I put `SP.SOD.executeFunc('sp.js', 'SP.ClientContext', () => { console.log("Done loading SP.ClientContext") })` and it worked.

I think one of the ways `CamlBuilder` works is by attaching `XmlWriter` to `SP`, but first one needs to make sure that `SP` has been loaded
