### ISSUE TITLE
InvalidOperationException when using OrderBy

### ISSUE THREAD

**Issue by johannes-z** [andrei-markeev/camljs#2]
I tried ordering the elements of a simple list by ID, but `camljs` throws an InvalidOperationException. In the chrome plugin, no caml query is generated.
```js 
var query = new CamlBuilder().View(['ID']).Query().OrderBy('ID').ToString()
```

![image](https://user-images.githubusercontent.com/9069888/31078040-e6e52818-a780-11e7-9e7e-353b6c37a93d.png)

**Comment by andrei-markeev** [comment]
Looks like a bug, thanks for reporting!

**Comment by andrei-markeev** [comment]
Should work now!

![image](https://user-images.githubusercontent.com/5181724/31202592-e6ed8da4-a96b-11e7-9c24-bf31dd5678f0.png)

**Comment by andrei-markeev** [comment]
https://github.com/andrei-markeev/camljs/releases/tag/2.8.1
