### ISSUE TITLE
ContentTypeId Field

### ISSUE THREAD

**Issue by ViceIce** [andrei-markeev/camljs#22]
Hi, it would be nice to use `<Value Type='ContentTypeId'>` at camljs, because this is the only working type on libraries.

* https://kerseub.wordpress.com/2013/06/28/using-contenttypeid-in-caml-query/

Regards
Michael

**Comment by andrei-markeev** [comment]
Do you have some steps how to reproduce a case where only "ContentTypeId" works, but not e.g. "Text"?

**Comment by ViceIce** [comment]
We are using a [SPSiteDataQuery](https://docs.microsoft.com/en-us/previous-versions/office/developer/sharepoint-2010/ms409088(v%3Doffice.14)) to query documents and items.

If we are using `Text` of `Computed` on custom lists, it will work, but if we query for contenttype of a library it will only work with `ContentTypeId` type.

We are filling the query properties `ViewFields`, `Lists` and `Webs` and we are using a startswith operator for the contenttypeid fetched from sitecollection contenttypes.

**Comment by andrei-markeev** [comment]
This is implemented and will be available in the next release.

Example of usage: https://github.com/andrei-markeev/camljs/blob/db34f2366248efe9e71df815732dd1f29deafa93/tests/Tests.ts#L620

Note: you may skip specifying internal name of the field here, in that case it will be "ContentTypeId" by default.
