### ISSUE TITLE
Chrome Extension

### ISSUE THREAD

**Issue by rlking1985** [andrei-markeev/camljs#23]
The chrome extension is no longer providing IntelliSense when building queries in the extension.

Not sure what is causing the issue and noticed it start since the last update.

![Uploading CamlJs Extension.PNG…]()

**Comment by rlking1985** [comment]
<img width="186" alt="CamlJs Extension" src="https://user-images.githubusercontent.com/6055618/54256954-cea5a180-45b1-11e9-899b-fcf813b500dd.PNG">

**Comment by andrei-markeev** [comment]
thanks for reporting, I'll look into this ASAP

**Comment by andrei-markeev** [comment]
Sorry, took some time. This should be fixed in extension v1.0.13

**Comment by rlking1985** [comment]
Thanks for the fix. Just tested the latest version and it is working again.

Cheers
