### ISSUE TITLE
FromXml doesn't work in node environments

### ISSUE THREAD

**Issue by lworkman** [andrei-markeev/camljs#25]
First of all, great library. Makes it way nicer to work with CAML.

I'm trying to use `FromXml` in a node environment and it's throwing a `window is not defined` error, which makes sense. It looks like the code relies upon `DOMParser`, which doesn't exist in node.

If this isn't a known issue (or there's no workaround), I'd be happy to help out and submit a PR. Let me know!

**Comment by andrei-markeev** [comment]
hey, I am super sorry for not responding for so long! I guess I was on vacation or smth, since I obviously couldn't reply right away and then forgot about it.

yes, PR is definitely appreciated!

**Comment by andrei-markeev** [comment]
Important note: I just checked, I do have a test for `FromXml` (`TestReplaceWhere()`). So before you start working on the fix, please try running `npm test` and if this test passes, then actually running `FromXml` is supported and then issue is something else.

**Comment by andrei-markeev** [comment]
Implemented as part of 2.12 (uses `xmldom` in order to support this in node env)

**Comment by lworkman** [comment]
Wow, thanks for this! Gonna be a huge help on my future projects 👍
