### ISSUE TITLE
OrderBy Descending is setting CAML Query to Ascending="False", should be Ascending="FALSE"

### ISSUE THREAD

**Issue by dsm0880** [andrei-markeev/camljs#26]
Hey,

Small bug. Typically this does not matter as SharePoint Online is case insensitive to this, but we have been battling this for a few days and finally tracked down the issue using Postman. For some task lists at our clients their is case sensitivity to the OrderBy Query. Basically just need to adjust Ascending="False" to Ascending="FALSE," all caps. For reference here is the Microsoft documentation referencing the expected values:

https://docs.microsoft.com/en-us/sharepoint/dev/schema/orderby-element-query

**Comment by dsm0880** [comment]
Yeah, never done that before. Let me try.

**Comment by dsm0880** [comment]
No, its a good exercise for me :) I've got the fix pushed to my branch, fixed the unit tests. Testing now.

**Comment by andrei-markeev** [comment]
thanks for the PR. I'll prepare the release and publish the new version asap.

**Comment by andrei-markeev** [comment]
hey, sorry for the delay, I decided to include one more improvement in the release and got a bit stuck with it. but now finally published 😃

**Comment by dsm0880** [comment]
Awesome, thanks @andrei-markeev
