### ISSUE TITLE
BooleanField gets improperly translated to Integer field

### ISSUE THREAD

**Issue by politicsruinseverything** [andrei-markeev/camljs#39]
CamlJS translates BooleanField('fieldname').EqualTo(true) into 
<Query>
   <Where>
      <Eq>
         <FieldRef Name='Follow_x002d_Up_x0020_Required' />
         <Value Type='Integer'>1</Value>
      </Eq>
   </Where>
</Query>

which does not return the proper values. I tested with U2U Caml Query Builder against SP 2013 and SP 2019 and found that the proper syntax should be 

<Query>
   <Where>
      <Eq>
         <FieldRef Name='Follow_x002d_Up_x0020_Required' />
         <Value Type='Boolean'>1</Value>
      </Eq>
   </Where>
</Query>

So, CamlJS gets it partly right by turning 'true' into '1' but it improperly marks the Value type as 'Integer'. It should be 'Boolean' since that is the type of field registered with SP. Otherwise, the wrong records are returned.

I am using the latest CamlJS of 2.12.0.

**Comment by politicsruinseverything** [comment]
After more experimenting, the Integer value seems to work pretty reliably. My apologies.

**Comment by andrei-markeev** [comment]
no problems 🙂
