### ISSUE TITLE
camljs is not working in an SPFx React WebPart

### ISSUE THREAD

**Issue by hbsts** [andrei-markeev/camljs#4]
I would like to use your extension in a SPFx React WebPart. 

I added your extension in the tsx file via import 'camljs'. I can use Intellisense and I added something like 
private abc = new CamlBuilder().View().Query().Where().LookupField("Ppp").Id().In([2,3,4]).ToString(); 
without a syntax error.

But after adding the webpart to the page I get errors:
...Failed to load entry point from component...CamlBuilder is not defined...

Do you have any idea how to fix this error?

**Comment by hbsts** [comment]
Sorry, I was too fast. Now it is working. I updated config/config.json:
...
  "externals": {
    "camljs":{
      "path" : "node_modules/camljs/camljs.js",
      "globalName": "camljs"
    }
  },
...

Now I am looking forward to work with your extension. CAML is really awful, but in my case better than ODATA. Thanks a lot for sharing your CAML generator!

**Comment by andrei-markeev** [comment]
FYI: starting from CamlJs v2.9.0, full Node.js support is added, so it is now possible to do `npm install camljs -S` and then use e.g.
```js
import * as CamlBuilder from 'camljs'
```
Full SPFx example here: https://github.com/andrei-markeev/camljs/tree/master/examples/spfx
