### ISSUE TITLE
npm issue (CamlBuilder not defined)

### ISSUE THREAD

**Issue by johannes-z** [andrei-markeev/camljs#6]
I'm using camljs in a commonjs/es6 environment, and `CamlBuilder` isn't exported correctly (or at all):

In `camljs.js`, there needs to be a `module.exports = CamlBuilder` and in `index.js` it should be:

```js
var CamlBuilder = require('./camljs');
module.exports = CamlBuilder;
```

Otherwise, CamlBuilder is undefined.

I would create a PR, but I don't know where the npm stuff is defined in this project.

**Comment by ViceIce** [comment]
See #10. npm package is owned by someone else.

**Comment by andrei-markeev** [comment]
Yes got the access now (this morning) and will address this issue in few days.

**Comment by andrei-markeev** [comment]
Should be possible now to use it in node normally.

For example:
```
npm i camljs
```
and then
```js
var CamlBuilder = require('camljs');
var query = new CamlBuilder().Where().TextField("Title").EqualTo("Hello").ToString();
console.log(query);
```
or same with ES6 syntax:
```ts
import * as CamlBuilder from 'camljs';
var query = new CamlBuilder().Where().TextField("Title").EqualTo("Hello").ToString();
console.log(query);
```

**Comment by johannes-z** [comment]
Can we get a default export for ES6 to do `import CamlBuilder from 'camljs'`?

**Comment by johannes-z** [comment]
You could do both however, like

```js
export { CamlBuilder };
// and
export default CamlBuilder
```

But it's fine either way.

Thanks for the fix of the npm package!

**Comment by ViceIce** [comment]
With Typescript 2.7 you can enable compiler flag [--esModuleInterop](http://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-form-commonjs-modules-with---esmoduleinterop) to use `import CamlBuilder from 'camljs';`
