### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ViceIce** [andrei-markeev/camljs#9]
Hi,

please add some licensing information to your repository. On the old codeplex page you licensed under [Ms-PL](https://en.wikipedia.org/wiki/Shared_source#Microsoft_Public_License_(Ms-PL)). What is the current license?

Regards
Michael

**Comment by ViceIce** [comment]
I would propose the [MIT License](https://en.wikipedia.org/wiki/MIT_License).

**Comment by andrei-markeev** [comment]
I am not actually managing the npm package, so please ignore this "ISC" for now.
The current license is Ms-PL, but I am OK to change it if it's necessary.
Is MIT better from compatibility point of view?

**Comment by ViceIce** [comment]
Ok. 

MIT is GPL compatible, Ms-PL is not. so i think switching to MIT would be a good idea.

**Comment by andrei-markeev** [comment]
For now updated to MS-PL everywhere and uploaded the license test. I am not a big expert in licenses so please allow me a bit more time to understand all implications and how it is done correctly.

**Comment by ViceIce** [comment]
No Problem. MS-PL is ok for us. 👍
